### ISSUE TITLE
% of plot composition that is allocated to Dr Plotter

### ISSUE THREAD

**Issue by digitalspaceport** [drnick23/drplotter#26]
Hi Dr Nick first off, nice new tech! Wild what GPUs can accomplish. I had a question for an upcoming video that I wanted to ask if you would care to divulge. I don't use discord, so posting here in lieu of that.

"Each DrPlot you create contains a small set of developer proofs, which will occasionally be solved just like one of your own proofs"

Can/will you let us know the composition % of each plot file this is? I have a guess it is 3% of each plot, but I wanted to give you an opportunity to answer this before I finish the part of the video talking about this.

Looking forward to growing a Dr Farm with my 3090s 😁

**Comment by drnick23** [comment]
Hi, thanks for getting in touch.

I answered this as best I could in the reddit AMA here:
https://www.reddit.com/r/chia/comments/1artu7g/comment/kqqtj5w/

It is a single digit percentage and it needs to stay competitive vs the other formats. Sometimes it's also not clear, that the end result is that the plots you make are net of fees, i.e. you take home 100% of the rewards based on the plot size and supported capacities.

**Comment by digitalspaceport** [comment]
I'm glad to read that it would be around 3.25% for CHIP-22 compat version of your software. I also respect you have an algorithmic distribution of your developer proofs that you are not disclosing to remain secure in your earnings currently. 

In the XCH.TODAY interview you just did, you did mention there would be a tool to convert plots once CHIP-22 is implemented vs needing to fully replot. We have heard this in the past and the energy utilized to convert would have been near the same/greater vs replotting. Either the plot file shrinks or the proofs are replaced and the plot file stays the same, and conveying that information to viewers is not easy with the unknown change in size/rewards distribution but I do need to tell them something, which at this point would be "we don't know". That may not be received well so just asking if you can provide any more clarity I can convey.

Do you have, even if it is rough, an ETA on when you expect to have the CHIP-22 compatible version released so folks can have a timeframe to expect to have full information around the (hopefully) long lived plot in?

**Comment by drnick23** [comment]
If the plot format switches to pure CHIP-22, then the plot formats can be
processed by CPU (no gpu needed) and reconfigured with minimal cost— the
time to create the formats for chip-22 optimized proofs would be just
slightly longer than copying to file, but could be done in parrallel or in
a background process without disruption to farming.

The exact CHIP-22 % isn’t set— I am assuming it may need to a be a fraction
like 1/32 or 1/64, I haven’t looked into the details yet, but if it’s
possible to use a custom percentage, then the fee would be set so either
the shrink in plot size would match the new fee (I.e. this would result in
0% change in fees) or in favor of the user (so they would net more after
the change). The original design ensured that fees could not be changed or
altered in the future so that the farmers could rely on steady results, and
my philosophy would carry forward in the same way.

As for the timeline this depends largely on demand— currently the system
works as designed, and farmers have free choice over which farming software
to use. There are some optimizations still coming and also areas that could
be improved like plotting and support for lower end GPUs, which might be
prioritized.

There may also be solutions to providing a local solver that doesn’t
require chip-22 and the random aspect of the fee on taking block rewards,
which some smaller farmers don’t like as they are more subject to the
potential for bad luck. Note that fees in chip-22 can also be changed with
different releases in software, and with the commitment in time to creating
plots, while I can personally assure the fee would remain stable, it’s not
as powerful as saying, “here’s your plot, what you see is what you get, the
generated rewards are yours to keep forever”.

A migration to chip-22 would be something I would check in with the
community and collect feedback on.

**Comment by digitalspaceport** [comment]
Thank you for thoughtful reply. I do think support for lower spec GPUs would make for a big impact for onboarding potential farmers into your system and be a priority, at least in my mind. I would assume both NoSSD and GH devs are working to achieve better compression levels as well right now. These are very interesting times in Chia indeed.
