### ISSUE TITLE
Was there an issue with 0.9.1? I notice its gone now.

### ISSUE THREAD

**Issue by digitalspaceport** [drnick23/drplotter#30]
Should revert back to 0.9.0 for now?

**Comment by drnick23** [comment]
A user was reporting issues and was on 0.9.1, and it was related to not getting proofs, so I took it down in case there were problems. However, it turns out they were just not connecting to their farmer properly, and it was unrelated. I'm still running 0.9.1 without issues, so if you got it before it was taken down it should bo ok.

In future, I'll do a pre-release version, that runs on a separate server and then migrate it to release once it's proven stable.
