### ISSUE TITLE
QUESTION: 90K C17 Plots, 3 x Harvesters - Am I a good candidate to replot with your software

### ISSUE THREAD

**Issue by rjsears** [drnick23/drplotter#7]
Hello - 

I have been reading up on your plotting software and solutions, but I am having a hard time trying to figure out if I would be a good candidate to move to your software.

I have three harvesters: one with the 4090, two with the 3090s, and an external remote_compute with 2 x A4000s. I have 90,000 C17 plots across those harvesters, roughly equally distributed. I chose c17, so when the filter changes, I am still good with those harvesters. I run a single farmer and pool with one of the pools. 

So my question is pretty simple, if I replotted with your Pro4X to get the most space savings, how many of the 4090s would I need to be able to handle the resultant number of plots and support my farm after the filter change? Replotting 90K plots would be a challenging task. Does your software also handle c17 plots, or would I have to down my entire farm to replot utilizing your software (or deploy more servers)?

Thanks for the information.

**Comment by drnick23** [comment]
The DrSolver cannot process other plot types for you, so it would need it's own dedicated GPU.

A 4090 can currently handle 200 raw TiB for Pro4x plots at the 256 filter. For 5000+ TiB you would need to setup a GPU farm of about 28 4090's. 

Since the new setup would be a lot different than your current one, you wouldn't be pulling down your existing system, you would be setting up a new system, mainly the 28 GPU's. I know 28 GPU's sounds like a lot, but you'd be running a 20PiB+ farm.

Right now we are at the 512 plot filter, which means you could setup 14 Plotting and solving machines that hold two 4090's each. An ideal plotter is a consumer gaming pc with 128GB ram, should be under $800 new. 

Then, you could start running each pc with one GPU running plots, and one GPU as a DrSolver. with all 14 Plotting, it would take a little over 30 days to plot. Initially, you wouldn't need to run all the solvers so a lot would sit idle unless you also want to add those to seperate plotting machines, but you would only save at most 10 days or so of plot time.

After 30 days you would have converted most of your farm and stayed running. When the plot filter hits, your plotting should be done and they all switch to solving.

**Comment by rjsears** [comment]
Thank You much for taking the time to explain it all!
